### ISSUE TITLE
Shopcards not showing up in dev and prod environments

### ISSUE THREAD

**Issue by Mordax** [carysmills/whentoshop#34]
I really like the project and I'm hoping to add some locations myself. 

I've noticed that running both the dev and prod environments yield this:
![whentoshop](https://user-images.githubusercontent.com/9853904/80823249-4e257400-8baa-11ea-8a8f-fb906bfea897.png)

The readme mentioned that you use a cron job to grab data, which I'm assuming goes to a `/data` folder (looking at the network requests). I tried placing one of the JSON data files (barrhaven.json, etc) to see if the Shopcards display, but I didn't get anything. 

Is this to be expected, or am I missing something?

**Comment by carysmills** [comment]
Hey @Mordax, sorry about that. I am planning to add better contribution guidelines soon.

You do need a data directory nested under the public directory like this
<img width="353" alt="Screen Shot 2020-05-01 at 6 00 35 PM" src="https://user-images.githubusercontent.com/12213371/80844909-d79e6b80-8bd5-11ea-8488-d2e474441826.png">

You can grab a data file from [here](https://whento.shop/data).

If you're still having issues after that, can you tell me what you see in your JS console in your browser?

**Comment by Mordax** [comment]
@carysmills The Readme cleared it up - had the data folder in the wrong place. Thanks!
