### ISSUE TITLE
Problem running python3 scraper.py

### ISSUE THREAD

**Issue by aelsabagh** [carysmills/whentoshop#43]
Hi Carys

I'm trying to make a similar version for Australia but running into a problem.

I want to change the locations, but whenever I run `python3 scraper.py`

I get the following result

`Traceback (most recent call last):
  File "scraper.py", line 1, in <module>
    import populartimes
ModuleNotFoundError: No module named 'populartimes'`

**Comment by carysmills** [comment]
Oh I will add this step to the instructions in the readme! You need to locally install `populartimes`, as per the instructions in that `README`. You can do so with this command `pip install --upgrade git+https://github.com/m-wrzr/populartimes`.

**Comment by aelsabagh** [comment]
Do you mean locally in the root folder? I've installed it but still getting the same error.

When I do: 

```
$ python3 scraper.py                                              
Traceback (most recent call last):
  File "scraper.py", line 1, in <module>
    import populartimes
ModuleNotFoundError: No module named 'populartimes'
```

I also try with python 2.7

```
$ python scraper.py                                              
Traceback (most recent call last):
  File "scraper.py", line 1, in <module>
    import populartimes
  File "/.../Python/2.7/lib/python/site-packages/populartimes/__init__.py", line 4, in <module>
    from .crawler import run
  File "/.../Python/2.7/lib/python/site-packages/populartimes/crawler.py", line 12, in <module>
    import urllib.request
ImportError: No module named request
```

**Comment by carysmills** [comment]
Yes in the `whentoshop` directory.
I think `populartimes` is only setup to work with python3. I just confirmed the instructions on another computer. Depending on your local setup, you may need to install `populartimes` explicitly using `pip3`. So you'd run the same installation command, but with `pip3` instead of `pip`.

**Comment by EricStG** [comment]
FYI I had to `pip install googlemaps` after installing populartimes to get the scrapper working

**Comment by aelsabagh** [comment]
Finally figured out how to do it!

For some reason it was trying to use python 2.7, so I  needed to get python3 to know about it.

```
python3 -m pip install --upgrade git+https://github.com/m-wrzr/populartimes 
```

```
python3 -m pip install googlemaps
````

**Comment by aelsabagh** [comment]
Thanks a lot for your help @EricStG @carysmills :)

**Comment by carysmills** [comment]
Hey @aelsabagh, could you please remove my Google Analytics tracking from your site?

**Comment by aelsabagh** [comment]
Yep my bad!
