### ISSUE TITLE
A few idea to make it easier to add locations

### ISSUE THREAD

**Issue by EricStG** [carysmills/whentoshop#45]
When adding a couple locations earlier, I have some thoughts on how it could be made easier

- [x] Add a requirements.txt file for the python dependencies
This way we can easily setup the environment using pip -r requirements.txt

- [x] Split Get IDs in its own script
Then we can get the ids from the location file without having to modify `scraper.py`

- [x] Allow to optionally pass a location to `scrapper.py`
To enable scrapping 1 location at a time

- [x] Store the locations in JSON format
More work upfront, but this way you could put it in public, and have it read by both the python and the react stacks. No need to update html/js anymore!

**Comment by carysmills** [comment]
Thanks! Totally agree with most of these - just haven’t had a chance to get to them yet 😀. I’ve been thinking about the JSON idea specifically.

**Comment by EricStG** [comment]
Well, I can help with any of there (or anything else). I find myself with a bit of extra free time these days... 🤷‍♂️

**Comment by carysmills** [comment]
Thank you! Now the requests for new locations have slowed down, I should be able to do this in the next few days, but I’ll let you know if I need help!

**Comment by carysmills** [comment]
@EricStG I made a separate function to get individual locations locally and have updated the readme to reflect it!

**Comment by EricStG** [comment]
Awesome work!
